Feature/rebuild setup mentions
Teyk0o/wwsnb pull request #13
Opened 2024-11-11 21:06 UTC by Mimouss56

Rework de Mention pour respecter le SOC

2024-11-11 21:10 UTC, Teyk0o requested changes
Pourquoi 26 fichiers ? Je pense qu'il y a un problème

2024-11-11 22:16 UTC, Mimouss56 commented
Ah oui il y a un souci, je regarderai demain, car il a pris toutes les modifications faites c'est bizarre

2024-11-11 22:18 UTC, Mimouss56 commented
J'avais pas vu que j'avais sélectionné master au lieu de develop désolé

2024-11-12 07:43 UTC, Teyk0o approved these changes

2024-11-12 07:43 UTC, merged